name: vcat  # Name of your Conda environment
channels:
  - conda-forge       
  - bioconda                    
dependencies:
  - python=3.11        
  - aria2
  - csvtk
  - seqkit
  - bbmap
  - taxopy
  - rapidfuzz
  - taxonkit=0.18.0
  - mmseqs2=17.b804f # upgraded from 15.6f452 
  - snakemake
  - seaborn
  - pyfastx       
  - click
  - dask
  - tqdm
  - biopython
  - ete3
  - openpyxl            
  - pyyaml            
  - pandas             
  - numpy              
  - matplotlib 
  - polars        
  - pip    
  - prodigal-gv
            
